name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
test
  build: android test 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
